services:
  redis:
    image: kmaku4/hackyeah-redis:latest
    container_name: redis-game
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]  # snapshoty RDB włączone
    privileged: true   # pozwala background jobs w Redis
    restart: unless-stopped

  fastapi:
    image: kmaku4/hackyeah-backend:latest
    container_name: fastapi-game
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # montujemy tylko katalog app, aby uvicorn widział moduł
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

volumes:
  redis_data:
