services:
  redis:
    image: kmaku4/hackyeah-redis:latest
    container_name: redis-game
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    privileged: true
    restart: unless-stopped

  fastapi:
    image: kmaku4/hackyeah-backend:latest
    container_name: fastapi-game
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # montujemy cały katalog projektu
    working_dir: /app  # katalog roboczy w kontenerze
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

volumes:
  redis_data:
