version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-game
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  fastapi:
    image: kmaku4/hackyeah-backend:latest
    container_name: fastapi-game
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      - redis
#    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  frontend:
    image: kmaku4/hackyeah-front:latest   
    container_name: nextjs-game
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "/api"   
    depends_on:
      - fastapi
    restart: unless-stopped

  nginx:
    image: kmaku4/hackyeah-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - fastapi

volumes:
  redis_data:
